language: r
sudo: false
cache: packages

r:
  - devel

os:
  - linux

branches:
  only:
    - master

# Be strict when checking our package, but don't build the manual
warnings_are_errors: true
# Note: can also add --no-build-vignettes to both
r_build_args: --no-manual --no-resave-data
r_check_args: --no-manual --as-cran

# Email notifications
notifications:
  email:
    on_success: change
    on_failure: change
     
# covr is not a dependency for the package. So, install it explicitly
r_binary_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
